defaults: &defaults
  apikey: [APIKEY]
  almaurl: https://api-na.hosted.exlibrisgroup.com/almaws/v1
  institution: [INSTITUTION]
  alma: na01
  root_url: [root url]
  alma_auth_secret: [auth secret for Oauth]
  SOLR_URL: [solr url]
  SUMMON_ACCESS_ID: [summon access id]
  SUMMON_SECRET_KEY: [summon secret key]  

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults